#!/bin/bash
if [ ! -z makefile ]; then
./configure  \
--host=arm-none-linux-gnueabi \
--with-kernel-support \
--with-extra-includes=$(pwd)/../../../../openlibs/include/ \
--with-extra-libs=$(pwd)/../../../../openlibs/lib/  \
--with-x \
CC=${CROSS_COMPILE}gcc CXX=${CROSS_COMPILE}g++
fi
