#!/bin/sh

export ac_cv_linux_vers=2.6.31 && \
./configure --host=arm-none-linux-gnueabi \
CFLAGS=-I$(pwd)/../../../../openlibs/include/ \
LDFLAGS=-L$(pwd)/../../../../openlibs/lib/ \
--oldincludedir=$(pwd) \
CC=${CROSS_COMPILE}gcc CXX=${CROSS_COMPILE}g++
