######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 21:21:26 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += wizard.h Wizard_dialog_test_X.h
SOURCES += main.cpp wizard.cpp Wizard_dialog_main.cpp Wizard_dialog_test_X.cpp
