######################################################################
# Automatically generated by qmake (1.07a) Fri May 21 17:01:54 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .


sprites.files = sprites
sprites.path = ../../../bin
INSTALLs +=sprites



# Input
HEADERS += Asteroid_test_X.h ledmeter.h sprites.h toplevel.h view.h
SOURCES += Asteroid_main.cpp \
           Asteroid_test_X.cpp \
           ledmeter.cpp \
           main.cpp \
           toplevel.cpp \
           view.cpp
