######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 11:53:23 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Pen_cap_test_test_X.h pencapmainwindow.h pencapmainwindowimpl.h
SOURCES += main.cpp \
           Pen_cap_test_main.cpp \
           Pen_cap_test_test_X.cpp \
           pencapmainwindow.cpp \
           pencapmainwindowimpl.cpp
