######################################################################
# Automatically generated by qmake (1.07a) Thu May 20 13:29:35 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .
LIBS += -lqassistantclient
# Input
HEADERS += Date_time_test_X.h DateTimeForm.h DateTimeView.h
SOURCES += Date_time_main.cpp \
           Date_time_test_X.cpp \
           DateTime.cpp \
           DateTimeForm.cpp \
           DateTimeView.cpp
