###################################################################################################
#
#    @file   Makefile
#
#    @brief  configuration file to compile the ARC USB file test.
#
###################################################################################################
#
#   Copyright (C) 2004, Freescale Semiconductor, Inc. All Rights Reserved
#   THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
#   BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
#   Freescale Semiconductor, Inc.
#
###################################################################################################
#Revision History:
#                            Modification     Tracking
#Author/core ID                  Date          Number    Description of Changes
#-------------------------   ------------    ----------  -------------------------------------------
#V.Khalabuda/b00306           17-07-2007     ENGR45124   Initial version
#
###################################################################################################
#Portability: ARM GCC
#
###################################################################################################
TARGET = usb_otg_host.sh

all:
	@echo "***********************************************"
	@echo "** ALL :     $(TARGET)                     **"
	@echo "***********************************************"
	@echo

install:
	@ln -f ./usb_otg_host.sh ../../../bin/usb_otg_host.sh
	@echo "***********************************************"
	@echo "** INSTALL : $(TARGET)                     **"
	@echo "***********************************************"
	@echo

clean:
	@echo "***********************************************"
	@echo "** CLEAN : $(TARGET)                     **"
	@echo "***********************************************"
	@echo
