#!/bin/sh
echo "--------------------"
export LTPROOT=$(pwd)
echo $LTPROOT
export STREAM_PATH=$(pwd)/../test_stream
export PATH=$PATH:$(pwd)/testcases/bin
export PATH=$PATH:$(pwd)/testscripts/common
export PATH=$PATH:$(pwd)/testscripts/common/storage_scripts/
echo "--------------------"
IPADDR=$(ifconfig -a eth0 | grep inet | sed -e 's/^.*addr://' -e 's/ .*$//')
echo "${LTPROOT}_$IPADDR at $(date +'%y%m%d')" >> /mnt/nfs/temp/.boardIP

