###################################################################################################

#

#    @file   Makefile

#

#    @brief  configuration file to compile the IrDA utils applications.

#

###################################################################################################

#

#   Copyright (C) 2004, Freescale Semiconductor, Inc. All Rights Reserved

#   THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT

#   BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF

#   Freescale Semiconductor, Inc.

#     

###################################################################################################

#Revision History:

#                            Modification     Tracking

#Author                          Date          Number    Description of Changes

#-------------------------   ------------    ----------  -------------------------------------------

#Vincent BECKER/rc023c  31/08/2004   TLSbo40417   Initial version 

#V. Becker/rc023c           27/09/2004   TLSbo40417   Inspection TLS941 

#L.Delaspre/rc149c            08/12/2004     TLSbo40142   update with Freescale identity

#

#

###################################################################################################

#Portability: Indicate if this module is portable to other compilers or platforms. 

#             If not, indicate specific reasons why is it not portable.

#

###################################################################################################



# SUBDIRS = irda-utils-0.9.16
SUBDIRS =

all:

#	@set -e; for i in $(SUBDIRS); do $(MAKE) -C $$i ; done



install:

#	@set -e; for i in $(SUBDIRS); do $(MAKE) -C $$i install ; done

	ln -f *.sh ../../bin

	@echo "***********************************************"

	@echo "** INSTALL IrDA test scripts                   **"

	@echo "***********************************************"

	@echo



clean:

#	@set -e; for i in $(SUBDIRS); do $(MAKE) -C $$i clean distclean; done

