#Copyright 2005-2009 Freescale Semiconductor, Inc. All Rights Reserved.
#
#The code contained herein is licensed under the GNU General Public
#License. You may obtain a copy of the GNU General Public License
#Version 2 or later at the following locations:
#
#http://www.opensource.org/licenses/gpl-license.html
#http://www.gnu.org/copyleft/gpl.html
###################################################################################################
#
#    @file   Makefile
#
#    @brief  configuration file to compile the IrDA utils applications.
#
###################################################################################################
#Revision History:
#                            Modification     Tracking
#Author                          Date          Number    Description of Changes
#-------------------------   ------------    ----------  -------------------------------------------
#Vincent BECKER/rc023c  31/08/2004   TLSbo40417   Initial version 
#V. Becker/rc023c           27/09/2004   TLSbo40417   Inspection TLS941 
#L.Delaspre/rc149c            08/12/2004     TLSbo40142   update with Freescale identity
#
#
###################################################################################################
#Portability: Indicate if this module is portable to other compilers or platforms. 
#             If not, indicate specific reasons why is it not portable.
#
###################################################################################################
# SUBDIRS = irda-utils-0.9.16
SUBDIRS =
all:
#	@set -e; for i in $(SUBDIRS); do $(MAKE) -C $$i ; done
install:
#	@set -e; for i in $(SUBDIRS); do $(MAKE) -C $$i install ; done
	ln -f *.sh ../../bin
	@echo "***********************************************"
	@echo "** INSTALL IrDA test scripts                   **"
	@echo "***********************************************"
	@echo
clean:
#	@set -e; for i in $(SUBDIRS); do $(MAKE) -C $$i clean distclean; done

