######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 11:24:26 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Fill_erase_test_X.h \
           rectfillingtestmainwindow.h \
           rectfillingtestmainwindowimpl.h
SOURCES += Fill_erase_main.cpp \
           Fill_erase_test_X.cpp \
           main.cpp \
           rectfillingtestmainwindow.cpp \
           rectfillingtestmainwindowimpl.cpp
