######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 14:39:38 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += canvas.h Canvas_test_X.h
SOURCES += canvas.cpp Canvas_main.cpp Canvas_test_X.cpp main.cpp
