#Copyright (C) 2007-2009 Freescale Semiconductor, Inc. All Rights Reserved.
#
#The code contained herein is licensed under the GNU General Public
#License. You may obtain a copy of the GNU General Public License
#Version 2 or later at the following locations:
#
#http://www.opensource.org/licenses/gpl-license.html
#http://www.gnu.org/copyleft/gpl.html
###################################################################################################
#
#    @file   Makefile
#
#    @brief  configuration file to compile the ARC USB file test.
#
###################################################################################################
#Revision History:
#                            Modification     Tracking
#Author/core ID                  Date          Number     Description of Changes
#-------------------------   ------------    -----------  -------------------------------------------
#A.Ozerov/b00320              18/07/2007      ENGR43014   Initial version
#
###################################################################################################
#Portability: ARM GCC
#
###################################################################################################
TARGET = usb_otg_gadget.sh

all:
	@echo "***********************************************"
	@echo "** ALL :     $(TARGET)                     **"
	@echo "***********************************************"
	@echo

install:
	@ln -f ./usb_otg_gadget.sh ../../../bin/usb_otg_gadget.sh
	@echo "***********************************************"
	@echo "** INSTALL : $(TARGET)                     **"
	@echo "***********************************************"
	@echo

clean:
	@echo "***********************************************"
	@echo "** CLEAN : $(TARGET)                     **"
	@echo "***********************************************"
	@echo
