###################################################################################################
#
#    @file   Makefile
#
#    @brief  configuration file to compile the DPM file test.
#
###################################################################################################
#
#   Copyright (C) 2004, Freescale Semiconductor, Inc. All Rights Reserved
#   THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
#   BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
#   Freescale Semiconductor, Inc.
#     
###################################################################################################
#Revision History:
#                            Modification     Tracking
#Author                          Date          Number    Description of Changes
#-------------------------   ------------    ----------  -------------------------------------------
#V.HALABUDA/-----             30-11-2004     TLSbo45067   Initial version
#
###################################################################################################
#Portability: Indicate if this module is portable to other compilers or platforms. 
#             If not, indicate specific reasons why is it not portable.
#
###################################################################################################

all:
	@echo "***********************************************"
	@echo "** ALL :     dpm_test.sh                     **"
	@echo "***********************************************"

install:
	@echo "***********************************************"
	@echo "** INSTALL : dpm_test.sh                     **"
	@echo "***********************************************"
	ln -f ./dpm_test.sh ../../../bin/dpm_test.sh
	@echo

clean:
