#Copyright 2005-2009 Freescale Semiconductor, Inc. All Rights Reserved.
#
#The code contained herein is licensed under the GNU General Public
#License. You may obtain a copy of the GNU General Public License
#Version 2 or later at the following locations:
#
#http://www.opensource.org/licenses/gpl-license.html
#http://www.gnu.org/copyleft/gpl.html
###################################################################################################
#
#    @file   Makefile
#
#    @brief  configuration file to compile the DPM file test.
#
###################################################################################################
#Revision History:
#                            Modification     Tracking
#Author                          Date          Number    Description of Changes
#-------------------------   ------------    ----------  -------------------------------------------
#V.HALABUDA/-----             30-11-2004     TLSbo45067   Initial version
#
###################################################################################################
#Portability: Indicate if this module is portable to other compilers or platforms. 
#             If not, indicate specific reasons why is it not portable.
#
###################################################################################################

all:
	@echo "***********************************************"
	@echo "** ALL :     dpm_test.sh                     **"
	@echo "***********************************************"

install:
	@echo "***********************************************"
	@echo "** INSTALL : dpm_test.sh                     **"
	@echo "***********************************************"
	ln -f ./dpm_test.sh ../../../bin/dpm_test.sh
	@echo

clean:
