
TARGET += display_clk.sh
TARGET += sd_clk.sh
TARGET += audio_clk.sh
TARGET += gpu_clk.sh
TARGET += vpu_clk.sh
TARGET += uart_clk.sh
TARGET += can_clk.sh
TARGET += usb_clk.sh
TARGET += i2c_clk.sh

all:

install:
	ln -f $(TARGET) ../../../bin/

clean:

