######################################################################
# Automatically generated by qmake (1.07a) Fri May 21 18:46:43 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += form.h Labels_Fonts_test.h rlayout.h
SOURCES += form.cpp Labels_Fonts_main.cpp Labels_Fonts_test.cpp rlayout.cpp
