######################################################################
# Automatically generated by qmake (1.07a) Thu May 20 10:42:40 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += checklists.h CheckLists_test.h
SOURCES += checklists.cpp CheckLists_main.cpp CheckLists_test.cpp
