######################################################################
# Automatically generated by qmake (1.07a) Tue Jul 27 17:57:54 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += splitter.h Splitter_test_X.h
SOURCES += splitter.cpp Splitter_main.cpp Splitter_test_X.cpp
