###################################################################################################
#
#    @file   Makefile
#
#    @brief  configuration file to compile the dvfs test.
#
###################################################################################################
#
#    Copyright (C) 2006, Freescale Semiconductor, Inc. All Rights Reserved
#    THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
#    BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
#    Freescale Semiconductor, Inc.
#
###################################################################################################
#Revision History:
#                            Modification     Tracking
#Author/core ID                  Date          Number    Description of Changes
#-------------------------   ------------    ----------  -------------------------------------------
#
all: 
install:
	ln -f dvfs.sh  ../../bin
	ln -f dvfs_mx25.sh ../../bin
	@echo "***********************************************"
	@echo "** INSTALL : dvfs.sh                    **"
	@echo "***********************************************"
	@echo

clean:
	@echo "***********************************************"
	@echo "** CLEAN : dvfs.sh                      **"
	@echo "***********************************************"
	@echo
