######################################################################
# Automatically generated by qmake (1.07a) Sat May 22 20:16:55 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += FileDialogTest_test.h FileDialogTestView.h
SOURCES += FileDialogTest_main.cpp \
           FileDialogTest_test.cpp \
           FileDialogTestView.cpp
