######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 09:59:12 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += hello.h Hello_test_test_X.h
SOURCES += hello.cpp Hello_test_main.cpp Hello_test_test_X.cpp main.cpp
