######################################################################
# Automatically generated by qmake (1.07a) Fri May 21 19:27:00 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += form.h Labels_TextFlags_test.h rlayout.h
SOURCES += form.cpp \
           Labels_TextFlags_main.cpp \
           Labels_TextFlags_test.cpp \
           rlayout.cpp
