
FILES = 800_480_s0.rgba32  \
        colorkey.s0        \
		large.s0           \
		small_w.s0         \
		tux_w.s1           \
		yuv420_640_480.s0  \
        800_480_s1.rgba32  \
		colorkey_w.s0      \
		large_w.s0         \
		small.s0           \
		tux.s1             \
		yuv420_352_240.s0  \
		fb-352x240.yuv     \
		rgb565_800_480.s1

all:
	
install:
	ln -f $(FILES) ../../../bin/
clean:
