###################################################################################################
#
#    @file   Makefile
#
#    @brief  configuration file to compile the VTE MMC test applications.
#
###################################################################################################
#
#   Copyright (C) 2004, Freescale Semiconductor, Inc. All Rights Reserved
#   THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
#   BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
#   Freescale Semiconductor, Inc.
#
###################################################################################################
#Revision History:
#                            Modification     Tracking
#Author                          Date          Number    Description of Changes
#-------------------------   ------------    ----------  -------------------------------------------
#S.ZAVJALOV/ZVJS001C          01/04/2005     TLSbo45047   Initial version
#
###################################################################################################

all:

install:
	@ln -f nominal_mmc_test.sh ../../../bin/nominal_mmc_test.sh

clean:
