######################################################################
# Automatically generated by qmake (1.07a) Sun May 23 14:05:20 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Tab_dialog_test_X.h tabdialog.h
SOURCES += main.cpp Tab_dialog_main.cpp Tab_dialog_test_X.cpp tabdialog.cpp
