######################################################################
# Automatically generated by qmake (1.07a) Fri Jul 16 10:12:39 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Transformations_test_X.h xform.h
SOURCES += Transformations_main.cpp Transformations_test_X.cpp xform.cpp
