######################################################################
# Automatically generated by qmake (1.07a) Sat May 22 20:16:05 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += DoubleOptionsForm.h \
           InputDialog_test.h \
           InputDialogView.h \
           IntegerOptionsForm.h
SOURCES += DoubleOptionsForm.cpp \
           InputDialog_main.cpp \
           InputDialog_test.cpp \
           InputDialogView.cpp \
           IntegerOptionsForm.cpp
