######################################################################
# Automatically generated by qmake (1.07a) Tue May 18 19:56:15 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += life.h Life_test_X.h lifedlg.h
SOURCES += life.cpp \
           Life_main.cpp \
           Life_test_X.cpp \
           lifedlg.cpp \
           main.cpp \
           patterns.cpp
