######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 19:29:44 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += cursor.h CursorView_test.h
SOURCES += cursor.cpp CursorView_main.cpp CursorView_test.cpp
