######################################################################
# Automatically generated by qmake (1.07a) Fri May 21 18:06:54 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += form.h Labels_Alignment_test.h rlayout.h
SOURCES += form.cpp \
           Labels_Alignment_main.cpp \
           Labels_Alignment_test.cpp \
           rlayout.cpp
