######################################################################
# Automatically generated by qmake (1.07a) Fri May 21 18:55:22 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += form.h Labels_Indent_test.h rlayout.h
SOURCES += form.cpp Labels_Indent_main.cpp Labels_Indent_test.cpp rlayout.cpp
