######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 12:00:12 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += ../../../../include
LIBS+= -L../../../../lib 
LIBS+= -lltp

# Input
HEADERS += PDTestView.h Stress_test_test_X.h
SOURCES += PDTestView.cpp \
           ProgressDialogTest.cpp \
           Stress_test_main.cpp \
           Stress_test_test_X.cpp

