######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 21:15:16 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += options.h options.ui.h Toplevel_test_test_X.h
SOURCES += main.cpp options.cpp Toplevel_test_main.cpp Toplevel_test_test_X.cpp
