######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 21:04:17 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += options.h options.ui.h
SOURCES += main.cpp options.cpp
