######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 16:34:33 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Editor_test_X.h textedit.h
SOURCES += Editor_main.cpp \
           Editor_test_X.cpp \
           main.cpp \
           qmake_image_collection.cpp \
           textedit.cpp
