#!/bin/sh
export CC=arm-none-linux-gnueabi-gcc
export AR="arm-none-linux-gnueabi-ar rc"
CFLAGS="$CFLAGS -fPIC" includedir=$(pwd)/../include \
prefix=$(pwd)/../ libdir=$(pwd)/../lib ./configure
unset CC
unset AR
