######################################################################
# Automatically generated by qmake (1.07a) Tue May 18 19:51:27 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += gtetrix.h qtetrix.h qtetrixb.h Tetrix_test_X.h tpiece.h
SOURCES += gtetrix.cpp \
           qtetrix.cpp \
           qtetrixb.cpp \
           tetrix.cpp \
           Tetrix_main.cpp \
           Tetrix_test_X.cpp \
           tpiece.cpp
