######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 09:22:33 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Timer_test_test_X.h TimerTest.h TimerView.h
SOURCES += Timer_test_main.cpp Timer_test_test_X.cpp TimerTest.cpp TimerView.cpp
