######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 21:13:25 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += dirview.h Dirview_test_test_X.h qdir.h
SOURCES += dirview.cpp Dirview_test_main.cpp Dirview_test_test_X.cpp qdir.cpp
