#Copyright 2008-2009 Freescale Semiconductor, Inc. All Rights Reserved.
#
#The code contained herein is licensed under the GNU General Public
#License. You may obtain a copy of the GNU General Public License
#Version 2 or later at the following locations:
#
#http://www.opensource.org/licenses/gpl-license.html
#http://www.gnu.org/copyleft/gpl.html
###################################################################################################
#
#    @file   Makefile
#
#    @brief  configuration file.
#
###################################################################################################
#Revision History:
#                            Modification     Tracking
#Author/core ID                  Date          Number     Description of Changes
#-------------------------   ------------    -----------  -------------------------------------------
#Hake Huang/B20222              02/12/2008                Initial version
#
###################################################################################################
#Portability: ARM GCC
#
###################################################################################################
TARGET = usb_otg_cdc.sh

all:
	@echo "***********************************************"
	@echo "** ALL :     $(TARGET)                     **"
	@echo "***********************************************"
	@echo

install:
	@ln -f $(TARGET) ../../../bin/
	@echo "***********************************************"
	@echo "** INSTALL : $(TARGET)                     **"
	@echo "***********************************************"
	@echo

clean:
	@echo "***********************************************"
	@echo "** CLEAN : $(TARGET)                     **"
	@echo "***********************************************"
	@echo
