######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 11:57:14 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Pen_color_test_test_X.h penmainwindow.h penmainwindowimpl.h
SOURCES += main.cpp \
           Pen_color_test_main.cpp \
           Pen_color_test_test_X.cpp \
           penmainwindow.cpp \
           penmainwindowimpl.cpp
