######################################################################
# Automatically generated by qmake (1.07a) Thu May 20 10:40:45 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += ButtonGroup_test.h buttongroups.h
SOURCES += ButtonGroup_main.cpp ButtonGroup_test.cpp buttongroups.cpp
