######################################################################
# Automatically generated by qmake (1.07a) Fri May 21 18:31:17 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += form.h Labels_Buddy_test.h rlayout.h
SOURCES += form.cpp Labels_Buddy_main.cpp Labels_Buddy_test.cpp rlayout.cpp
