######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 11:38:08 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Font_metrics_test_X.h \
           fontmetricstestmainwindow.h \
           fontmetricstestmainwindowimpl.h
SOURCES += Font_metrics_main.cpp \
           Font_metrics_test_X.cpp \
           fontmetricstestmainwindow.cpp \
           fontmetricstestmainwindowimpl.cpp \
           main.cpp
