######################################################################
# Automatically generated by qmake (1.07a) Fri May 21 19:34:59 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += form.h Labels_TextFormat_test.h rlayout.h
SOURCES += form.cpp \
           Labels_TextFormat_main.cpp \
           Labels_TextFormat_test.cpp \
           rlayout.cpp
