#!/bin/sh

if [ ! -e Makefile ]; then
./configure --host=arm-none-linux-gnueabi \
CFLAGS="-I../zlib-1.2.3" \
CXXFLAGS="-I../zlib-1.2.3" \
CPPFLAGS="-I../zlib-1.2.3" \
LDFLAGS="-L../lib" \
CC=${CROSS_COMPILE}gcc \
CXX=${CROSS_COMPILE}g++ \
--prefix=$(pwd)/../
fi
