#Copyright (C) 2005-2009 Freescale Semiconductor, Inc. All Rights Reserved.
#
#The code contained herein is licensed under the GNU General Public
#License. You may obtain a copy of the GNU General Public License
#Version 2 or later at the following locations:
#
#http://www.opensource.org/licenses/gpl-license.html
#http://www.gnu.org/copyleft/gpl.html
# list of platforms which want this test case
#CC = arm-none-linux-gnueabi-gcc
#KLINUX_SRCDIR = /home/vobs/linux-2.6-imx/

OBJDIR = ../../../bin/

SCRIPTS = ipu_test.sh

all:

install:
	ln -f $(SCRIPTS) $(OBJDIR)


.PHONY: clean
clean:

