# list of platforms which want this test case
#CC = arm-none-linux-gnueabi-gcc
#KLINUX_SRCDIR = /home/vobs/linux-2.6-imx/

OBJDIR = ../../../bin/

SCRIPTS = ipu_test.sh

all:

install:
	ln -f $(SCRIPTS) $(OBJDIR)


.PHONY: clean
clean:

