###################################################################################################
#
#    @file   Makefile
#
#    @brief  configuration file for UART applications.
#
###################################################################################################
#
#   Copyright (C) 2004, Freescale Semiconductor, Inc. All Rights Reserved
#   THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
#   BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
#   Freescale Semiconductor, Inc.
#     
###################################################################################################
#Revision History:
#                            Modification     Tracking
#Author                          Date          Number    Description of Changes
#-------------------------   ------------    ----------  -------------------------------------------
#Rakesh S Joshi		     04/05/2007       ENGR37562   Initial version 
#
#
###################################################################################################
#Portability: Indicate if this module is portable to other compilers or platforms. 
#             If not, indicate specific reasons why is it not portable.
#
###################################################################################################
# SUBDIRS = irda-utils-0.9.16
SUBDIRS =

all:
#	@set -e; for i in $(SUBDIRS); do $(MAKE) -C $$i ; done
install:
#	@set -e; for i in $(SUBDIRS); do $(MAKE) -C $$i install ; done

	ln -f *.sh ../../../bin

	@echo "***********************************************"

	@echo "** INSTALL UART_TESTAPP_8  scripts                   **"

	@echo "***********************************************"

	@echo



clean:
#	@set -e; for i in $(SUBDIRS); do $(MAKE) -C $$i clean distclean; done

