
FILES = blue_RGB565  \
		cyan_RGB32   \
		green_BGR24  \
		green_RGB24  \
		red_BGR24    \
		white_RGB24  \
		yellow_BGR32 \
		yuv420       \
		yuv422p
all:
	
install:
	ln -f $(FILES) ../../../bin/
clean:
