######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 10:45:40 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Brush_test_test_X.h brushtestmainwindow.h brushtestmainwindowimpl.h
SOURCES += Brush_test_main.cpp \
           Brush_test_test_X.cpp \
           brushtestmainwindow.cpp \
           brushtestmainwindowimpl.cpp \
           main.cpp
