######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 21:17:32 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += canvas.h \
           scribble.h \
           Tablet_test_test_X.h \
           tabletstats.h \
           tabletstatsbase.h
SOURCES += canvas.cpp \
           main.cpp \
           scribble.cpp \
           Tablet_test_main.cpp \
           Tablet_test_test_X.cpp \
           tabletstats.cpp \
           tabletstatsbase.cpp
