######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 11:42:29 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Font_test_test_X.h fonttestmainwindow.h fonttestmainwindowimpl.h
SOURCES += Font_test_main.cpp \
           Font_test_test_X.cpp \
           fonttestmainwindow.cpp \
           fonttestmainwindowimpl.cpp \
           main.cpp
