######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 11:04:24 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Draw_figures_test_X.h \
           drawfigurestestmainwindow.h \
           drawfigurestestmainwindowimpl.h
SOURCES += Draw_figures_main.cpp \
           Draw_figures_test_X.cpp \
           drawfigurestestmainwindow.cpp \
           drawfigurestestmainwindowimpl.cpp \
           main.cpp
