#!/bin/ksh

typeset -x BLDIR="Tools/dt.d-WIP"
typeset -x PROGRAM="dt"

OSs=$(uname -s)
if [ "$OSs" = "HP-UX" ] ; then
    typeset -x REMCMD="remsh"
else
    typeset -x REMCMD="rsh"
fi

makeit()
{
    if [ $# -lt 3 ]; then
	print "Usage: makeit SUBDIR MAKEXT BLDSYS"
	exit 1
    fi

    SUBDIR=$1
    OSNAME=$2
    BLDSYS=$3

    # Build directories are remotely mounted on each build system,
    # so it's safe to check for and create build subdirectory here.

    if [ ! -d $SUBDIR ]; then
	mkdir $SUBDIR
    fi

    # Execute the Makefile specific to the OS specified.

    print "\n\t--> Building '$PROGRAM' for $OSNAME on $BLDSYS in subdirectory $SUBDIR <--\n"

    $REMCMD $BLDSYS -n "cd ~/$BLDIR/$SUBDIR; umask 022; PATH=/usr/local/bin:$PATH ; make -f ../Makefile.$OSNAME VPATH=.."

    return
}

# ppc AIX 5.3

makeit aix5.3 aix-aio shaix11

# ppc AIX 5.2

makeit aix5.2 aix-aio ibmp505-fak01

# pa HP-UX 11.00

makeit hpux-parisc hpux shopvac

# ia64 HP-UX 11.23

makeit hpux-ia64 hpux-ia64 bissell

# i386 Linux

makeit linux2.4-x86 linux crunch

# ia64 Linux

#makeit linux-ia64 linux 15.11.146.54 # antares.fc.hp.com

# alpha Tru64 5.1B

#makeit tru64 zuluos evinrude

# sparc Solaris 5.8

#makeit solaris-sparc solaris roanoke
#makeit solaris-sparc solaris-aio roanoke
makeit solaris-sparc solaris-aio shsun03

# x86 Solaris

makeit solaris-x86 solaris-x86-aio l22.rtp.netapp.com

exit $?
