#!/bin/ksh
typeset disk=/dev/rrz2c
typeset limit=1g
rm -f /var/tmp/[123456789]g.log
dt of=$disk min=b max=64k incr=7k aios=8 iotype=random lba=0 rlimit=1g limit=$limit pattern=0x00ff00f log=/var/tmp/1g.log &
dt of=$disk min=b max=64k incr=7k aios=8 iotype=random position=1g rlimit=2g limit=$limit pattern=0x0f0f0f0f log=/var/tmp/2g.log &
dt of=$disk min=b max=64k incr=7k aios=8 iotype=random position=2g rlimit=3g limit=$limit pattern=0xc6dec6de log=/var/tmp/3g.log &
dt of=$disk min=b max=64k incr=7k aios=8 iotype=random position=3g rlimit=4g limit=$limit pattern=0x6db6db6d log=/var/tmp/4g.log &
dt of=$disk min=b max=64k incr=7k aios=8 iotype=random position=4g rlimit=5g limit=$limit pattern=0xaaaaaaaa log=/var/tmp/5g.log &
dt of=$disk min=b max=64k incr=7k aios=8 iotype=random position=5g rlimit=6g limit=$limit pattern=0x33333333 log=/var/tmp/6g.log &
dt of=$disk min=b max=64k incr=7k aios=8 iotype=random position=6g rlimit=7g limit=$limit pattern=0x26673333 log=/var/tmp/7g.log &
dt of=$disk min=b max=64k incr=7k aios=8 iotype=random position=8g rlimit=9g limit=$limit pattern=0x66673326 log=/var/tmp/8g.log &
dt of=$disk min=b max=64k incr=7k aios=8 iotype=random position=9g rlimit=17g limit=$limit pattern=0x71c7c71c log=/var/tmp/9g.log &

