######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 09:46:06 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += aclock.h clock.h dclock.h Timer_test_test_X.h
SOURCES += aclock.cpp \
           clock.cpp \
           dclock.cpp \
           main.cpp \
           Timer_test_main.cpp \
           Timer_test_test_X.cpp
