/* (c) Freescale 2004
 *
 *  MMDO-EMEA Fix : The symbols in the AMR-NB codec clashed with already existing
 *                  symbols in Trinity Convergence's multimedia framework
 *
 *		    This 'patch' provides a global symbol renaaming and should
 *		    avoid further such problems.
 *		    This technique can also be applied in order to make the AMR-NB
 *		    codec openMAX compliant
 *
 *
 *  Authors: Klaus Foerster (r26375) Patrice Bertrand (r34206)
 *  Note:    Look at GCC specific modification in lsp_lsf.c
*/

#ifndef _TRANSLATEGLOBALSYMBOLS_H_
#define _TRANSLATEGLOBALSYMBOLS_H_

#define abs_s fsl_amrnb_abs_s
#define add16_16_32 fsl_amrnb_add16_16_32
#define add fsl_amrnb_add
#define add_hi fsl_amrnb_add_hi
#define add_lo fsl_amrnb_add_lo
#define agc2 fsl_amrnb_agc2
#define agc fsl_amrnb_agc
#define agc_init fsl_amrnb_agc_init
#define agc_reset fsl_amrnb_agc_reset
#define A_Refl fsl_amrnb_A_Refl
#define Autocorr fsl_amrnb_Autocorr
#define Az_lsp fsl_amrnb_Az_lsp
#define Bgn_scd fsl_amrnb_Bgn_scd
#define Bgn_scd_init fsl_amrnb_Bgn_scd_init
#define Bgn_scd_reset fsl_amrnb_Bgn_scd_reset
#define Bits2prm fsl_amrnb_Bits2prm
#define build_CN_code fsl_amrnb_build_CN_code
#define build_CN_param fsl_amrnb_build_CN_param
#define calc_filt_energies fsl_amrnb_calc_filt_energies
#define calc_target_energy fsl_amrnb_calc_target_energy
#define calc_unfilt_energies fsl_amrnb_calc_unfilt_energies
#define Cb_gain_average fsl_amrnb_Cb_gain_average
#define Cb_gain_average_init fsl_amrnb_Cb_gain_average_init
#define Cb_gain_average_reset fsl_amrnb_Cb_gain_average_reset
#define cbsearch fsl_amrnb_cbsearch
#define c_fft fsl_amrnb_c_fft
#define check_gp_clipping fsl_amrnb_check_gp_clipping
#define check_lsp fsl_amrnb_check_lsp
#define cl_ltp fsl_amrnb_cl_ltp
#define cl_ltp_init fsl_amrnb_cl_ltp_init
#define cl_ltp_reset fsl_amrnb_cl_ltp_reset
#define cod_amr_first fsl_amrnb_cod_amr_first
#define cod_amr fsl_amrnb_cod_amr
#define cod_amr_init fsl_amrnb_cod_amr_init
#define cod_amr_reset fsl_amrnb_cod_amr_reset
#define code_10i40_35bits fsl_amrnb_code_10i40_35bits
#define code_2i40_11bits fsl_amrnb_code_2i40_11bits
#define code_2i40_9bits fsl_amrnb_code_2i40_9bits
#define code_3i40_14bits fsl_amrnb_code_3i40_14bits
#define code_4i40_17bits fsl_amrnb_code_4i40_17bits
#define code_8i40_31bits fsl_amrnb_code_8i40_31bits
#define comp_corr fsl_amrnb_comp_corr
#define Convolve fsl_amrnb_Convolve
#define Copy fsl_amrnb_Copy
#define cor_h fsl_amrnb_cor_h
#define cor_h_x2 fsl_amrnb_cor_h_x2
#define cor_h_x fsl_amrnb_cor_h_x
#define dec_10i40_35bits fsl_amrnb_dec_10i40_35bits
#define dec_8i40_31bits fsl_amrnb_dec_8i40_31bits
#define Dec_gain fsl_amrnb_Dec_gain
#define Dec_lag3 fsl_amrnb_Dec_lag3
#define Dec_lag6 fsl_amrnb_Dec_lag6
#define decode_2i40_11bits fsl_amrnb_decode_2i40_11bits
#define decode_2i40_9bits fsl_amrnb_decode_2i40_9bits
#define decode_3i40_14bits fsl_amrnb_decode_3i40_14bits
#define decode_4i40_17bits fsl_amrnb_decode_4i40_17bits
#define Decoder_amr fsl_amrnb_Decoder_amr
#define Decoder_amr_init fsl_amrnb_Decoder_amr_init
#define Decoder_amr_reset fsl_amrnb_Decoder_amr_reset
#define decoder_homing_frame_test_first fsl_amrnb_decoder_homing_frame_test_first
#define decoder_homing_frame_test fsl_amrnb_decoder_homing_frame_test
#define DeltaWeightedOperation fsl_amrnb_DeltaWeightedOperation
#define d_gain_code fsl_amrnb_d_gain_code
#define d_gain_pitch fsl_amrnb_d_gain_pitch
#define Div_32 fsl_amrnb_Div_32
#define div_s fsl_amrnb_div_s
#define D_plsf_3 fsl_amrnb_D_plsf_3
#define D_plsf_5 fsl_amrnb_D_plsf_5
#define D_plsf_init fsl_amrnb_D_plsf_init
#define D_plsf_reset fsl_amrnb_D_plsf_reset
#define dtx_buffer fsl_amrnb_dtx_buffer
#define dtx_dec_activity_update fsl_amrnb_dtx_dec_activity_update
#define dtx_dec fsl_amrnb_dtx_dec
#define dtx_dec_init fsl_amrnb_dtx_dec_init
#define dtx_dec_reset fsl_amrnb_dtx_dec_reset
#define dtx_enc fsl_amrnb_dtx_enc
#define dtx_enc_init fsl_amrnb_dtx_enc_init
#define dtx_enc_reset fsl_amrnb_dtx_enc_reset
#define dumfprintf fsl_amrnb_dumfprintf
#define dumprintf fsl_amrnb_dumprintf
#define eAMRDDecodeFrame fsl_amrnb_eAMRDDecodeFrame
#define eAMRDDecodeInit fsl_amrnb_eAMRDDecodeInit
#define eAMRDQueryMem fsl_amrnb_eAMRDQueryMem
#define eAMRDStateMemAssign fsl_amrnb_eAMRDStateMemAssign
#define eAMREEncodeFrame fsl_amrnb_eAMREEncodeFrame
#define eAMREEncodeInit fsl_amrnb_eAMREEncodeInit
#define eAMREQueryMem fsl_amrnb_eAMREQueryMem
#define eAMREStateMemAssign fsl_amrnb_eAMREStateMemAssign
#define ec_gain_code fsl_amrnb_ec_gain_code
#define ec_gain_code_init fsl_amrnb_ec_gain_code_init
#define ec_gain_code_reset fsl_amrnb_ec_gain_code_reset
#define ec_gain_code_update fsl_amrnb_ec_gain_code_update
#define ec_gain_pitch fsl_amrnb_ec_gain_pitch
#define ec_gain_pitch_init fsl_amrnb_ec_gain_pitch_init
#define ec_gain_pitch_reset fsl_amrnb_ec_gain_pitch_reset
#define ec_gain_pitch_update fsl_amrnb_ec_gain_pitch_update
#define Enc_lag3 fsl_amrnb_Enc_lag3
#define Enc_lag6 fsl_amrnb_Enc_lag6
#define encoder_homing_frame_test fsl_amrnb_encoder_homing_frame_test
#define eTxToRx fsl_amrnb_eTxToRx
#define Ex_ctrl fsl_amrnb_Ex_ctrl
#define extract_h fsl_amrnb_extract_h
#define extract_l fsl_amrnb_extract_l
#define gain_adapt fsl_amrnb_gain_adapt
#define gain_adapt_init fsl_amrnb_gain_adapt_init
#define gain_adapt_reset fsl_amrnb_gain_adapt_reset
#define gainQuant fsl_amrnb_gainQuant
#define gainQuant_init fsl_amrnb_gainQuant_init
#define gainQuant_reset fsl_amrnb_gainQuant_reset
#define G_code fsl_amrnb_G_code
#define gc_pred_average_limited fsl_amrnb_gc_pred_average_limited
#define gc_pred_copy fsl_amrnb_gc_pred_copy
#define gc_pred fsl_amrnb_gc_pred
#define gc_pred_init fsl_amrnb_gc_pred_init
#define gc_pred_reset fsl_amrnb_gc_pred_reset
#define gc_pred_update fsl_amrnb_gc_pred_update
#define getCounterId fsl_amrnb_getCounterId
#define get_vadname fsl_amrnb_get_vadname
#define gmed_n fsl_amrnb_gmed_n
#define G_pitch fsl_amrnb_G_pitch
#define hp_max fsl_amrnb_hp_max
#define Init_D_plsf_3 fsl_amrnb_Init_D_plsf_3
#define Init_WMOPS_counter fsl_amrnb_Init_WMOPS_counter
#define Interpol_3or6 fsl_amrnb_Interpol_3or6
#define Int_lpc_1and3_2 fsl_amrnb_Int_lpc_1and3_2
#define Int_lpc_1and3 fsl_amrnb_Int_lpc_1and3
#define Int_lpc_1to3_2 fsl_amrnb_Int_lpc_1to3_2
#define Int_lpc_1to3 fsl_amrnb_Int_lpc_1to3
#define Int_lsf fsl_amrnb_Int_lsf
#define Inv_sqrt fsl_amrnb_Inv_sqrt
#define L_abs fsl_amrnb_L_abs
#define L_add fsl_amrnb_L_add
#define Lag_window fsl_amrnb_Lag_window
#define L_Comp fsl_amrnb_L_Comp
#define L_deposit_h fsl_amrnb_L_deposit_h
#define L_deposit_l fsl_amrnb_L_deposit_l
#define Levinson fsl_amrnb_Levinson
#define Levinson_init fsl_amrnb_Levinson_init
#define Levinson_reset fsl_amrnb_Levinson_reset
#define L_Extract fsl_amrnb_L_Extract
#define L_mac_32 fsl_amrnb_L_mac_32
#define L_mac fsl_amrnb_L_mac
#define L_mac_hi fsl_amrnb_L_mac_hi
#define L_mac_lo fsl_amrnb_L_mac_lo
#define L_msu fsl_amrnb_L_msu
#define L_mult_32 fsl_amrnb_L_mult_32
#define L_mult fsl_amrnb_L_mult
#define L_negate fsl_amrnb_L_negate
#define Log2 fsl_amrnb_Log2
#define Log2_norm fsl_amrnb_Log2_norm
#define logic16 fsl_amrnb_logic16
#define logic32 fsl_amrnb_logic32
#define lpc fsl_amrnb_lpc
#define lpc_init fsl_amrnb_lpc_init
#define lpc_reset fsl_amrnb_lpc_reset
#define Lsf_lsp fsl_amrnb_Lsf_lsp
#define Lsf_wt fsl_amrnb_Lsf_wt
#define L_shl9 fsl_amrnb_L_shl9
#define L_shl fsl_amrnb_L_shl
#define L_shr fsl_amrnb_L_shr
#define L_shr_r fsl_amrnb_L_shr_r
#define lsp_avg fsl_amrnb_lsp_avg
#define lsp_avg_init fsl_amrnb_lsp_avg_init
#define lsp_avg_reset fsl_amrnb_lsp_avg_reset
#define Lsp_Az fsl_amrnb_Lsp_Az
#define lsp fsl_amrnb_lsp
#define lsp_init fsl_amrnb_lsp_init
#define Lsp_lsf fsl_amrnb_Lsp_lsf
#define lsp_reset fsl_amrnb_lsp_reset
#define L_sub fsl_amrnb_L_sub
#define Mac_32_16 fsl_amrnb_Mac_32_16
#define Mac_32 fsl_amrnb_Mac_32
#define mac_r fsl_amrnb_mac_r
#define mode2str fsl_amrnb_mode2str
#define move16 fsl_amrnb_move16
#define move32 fsl_amrnb_move32
#define Mpy_32_16 fsl_amrnb_Mpy_32_16
#define Mpy_32 fsl_amrnb_Mpy_32
#define MR475_gain_quant fsl_amrnb_MR475_gain_quant
#define MR475_update_unq_pred fsl_amrnb_MR475_update_unq_pred
#define MR795_gain_quant fsl_amrnb_MR795_gain_quant
#define msu_r fsl_amrnb_msu_r
#define mult32_32_32 fsl_amrnb_mult32_32_32
#define mult fsl_amrnb_mult
#define mult_r fsl_amrnb_mult_r
#define negate fsl_amrnb_negate
#define Norm_Corr fsl_amrnb_Norm_Corr
#define norm_l fsl_amrnb_norm_l
#define norm_s fsl_amrnb_norm_s
#define ol_ltp fsl_amrnb_ol_ltp
#define out fsl_amrnb_out
#define ph_disp fsl_amrnb_ph_disp
#define ph_disp_init fsl_amrnb_ph_disp_init
#define ph_disp_lock fsl_amrnb_ph_disp_lock
#define ph_disp_release fsl_amrnb_ph_disp_release
#define ph_disp_reset fsl_amrnb_ph_disp_reset
#define Pitch_fr fsl_amrnb_Pitch_fr
#define Pitch_fr_init fsl_amrnb_Pitch_fr_init
#define Pitch_fr_reset fsl_amrnb_Pitch_fr_reset
#define Pitch_ol fsl_amrnb_Pitch_ol
#define Pitch_ol_wgh fsl_amrnb_Pitch_ol_wgh
#define p_ol_wgh_init fsl_amrnb_p_ol_wgh_init
#define p_ol_wgh_reset fsl_amrnb_p_ol_wgh_reset
#define Post_Filter fsl_amrnb_Post_Filter
#define Post_Filter_init fsl_amrnb_Post_Filter_init
#define Post_Filter_reset fsl_amrnb_Post_Filter_reset
#define Post_Process fsl_amrnb_Post_Process
#define Post_Process_init fsl_amrnb_Post_Process_init
#define Post_Process_reset fsl_amrnb_Post_Process_reset
#define Pow2 fsl_amrnb_Pow2
#define pre_big fsl_amrnb_pre_big
#define Pred_lt_3or6 fsl_amrnb_Pred_lt_3or6
#define preemphasis fsl_amrnb_preemphasis
#define preemphasis_init fsl_amrnb_preemphasis_init
#define preemphasis_reset fsl_amrnb_preemphasis_reset
#define Pre_Process fsl_amrnb_Pre_Process
#define Pre_Process_init fsl_amrnb_Pre_Process_init
#define Pre_Process_reset fsl_amrnb_Pre_Process_reset
#define Prm2bits fsl_amrnb_Prm2bits
#define proc_head fsl_amrnb_proc_head
#define pseudonoise fsl_amrnb_pseudonoise
#define q_gain_code fsl_amrnb_q_gain_code
#define q_gain_pitch fsl_amrnb_q_gain_pitch
#define q_p fsl_amrnb_q_p
#define Q_plsf_3 fsl_amrnb_Q_plsf_3
#define Q_plsf_5 fsl_amrnb_Q_plsf_5
#define Q_plsf_init fsl_amrnb_Q_plsf_init
#define Q_plsf_reset fsl_amrnb_Q_plsf_reset
#define Qua_gain fsl_amrnb_Qua_gain
#define Reorder_lsf fsl_amrnb_Reorder_lsf
#define Reset_WMOPS_counter fsl_amrnb_Reset_WMOPS_counter
#define Residu fsl_amrnb_Residu
#define r_fft fsl_amrnb_r_fft
#define rnd fsl_amrnb_rnd
#define rr_write fsl_amrnb_rr_write
#define rx_dtx_handler fsl_amrnb_rx_dtx_handler
#define rxframe2str fsl_amrnb_rxframe2str
#define saturate fsl_amrnb_saturate
#define search_10and8i40 fsl_amrnb_search_10and8i40
#define setCounter fsl_amrnb_setCounter
#define set_sign12k2 fsl_amrnb_set_sign12k2
#define set_sign fsl_amrnb_set_sign
#define Set_zero fsl_amrnb_Set_zero
#define shl fsl_amrnb_shl
#define shr fsl_amrnb_shr
#define shr_r fsl_amrnb_shr_r
#define sid_sync_exit fsl_amrnb_sid_sync_exit
#define sid_sync fsl_amrnb_sid_sync
#define sid_sync_init fsl_amrnb_sid_sync_init
#define sid_sync_reset fsl_amrnb_sid_sync_reset
#define sid_sync_set_handover_debt fsl_amrnb_sid_sync_set_handover_debt
#define Speech_Decode_Frame_exit fsl_amrnb_Speech_Decode_Frame_exit
#define Speech_Decode_Frame fsl_amrnb_Speech_Decode_Frame
#define Speech_Decode_Frame_init fsl_amrnb_Speech_Decode_Frame_init
#define Speech_Decode_Frame_reset fsl_amrnb_Speech_Decode_Frame_reset
#define Speech_Encode_Frame_exit fsl_amrnb_Speech_Encode_Frame_exit
#define Speech_Encode_Frame fsl_amrnb_Speech_Encode_Frame
#define Speech_Encode_Frame_init fsl_amrnb_Speech_Encode_Frame_init
#define Speech_Encode_Frame_reset fsl_amrnb_Speech_Encode_Frame_reset
#define sqrt_l_exp fsl_amrnb_sqrt_l_exp
#define str2mode fsl_amrnb_str2mode
#define sub16_hi fsl_amrnb_sub16_hi
#define sub16_lo fsl_amrnb_sub16_lo
#define subframePostProc fsl_amrnb_subframePostProc
#define subframePreProc fsl_amrnb_subframePreProc
#define sub fsl_amrnb_sub
#define sub_hi fsl_amrnb_sub_hi
#define sub_lo fsl_amrnb_sub_lo
#define Syn_filt fsl_amrnb_Syn_filt
#define test fsl_amrnb_test
#define ton_stab_init fsl_amrnb_ton_stab_init
#define ton_stab_reset fsl_amrnb_ton_stab_reset
#define TotalWeightedOperation fsl_amrnb_TotalWeightedOperation
#define t_shl fsl_amrnb_t_shl
#define tx_dtx_handler fsl_amrnb_tx_dtx_handler
#define txframe2str fsl_amrnb_txframe2str
#define update_gp_clipping fsl_amrnb_update_gp_clipping
#define vad1 fsl_amrnb_vad1
#define vad1_init fsl_amrnb_vad1_init
#define vad1_reset fsl_amrnb_vad1_reset
#define vad_complex_detection_update fsl_amrnb_vad_complex_detection_update
#define vad_pitch_detection fsl_amrnb_vad_pitch_detection
#define vad_tone_detection fsl_amrnb_vad_tone_detection
#define vad_tone_detection_update fsl_amrnb_vad_tone_detection_update
#define Weight_Ai fsl_amrnb_Weight_Ai
#define WMOPS_output fsl_amrnb_WMOPS_output

#endif /* _TRANSLATEGLOBALSYMBOLS_H_ */
