######################################################################
# Automatically generated by qmake (1.07a) Tue Jul 27 18:02:27 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += table.h Table_test_X.h
SOURCES += table.cpp Table_main.cpp Table_test_X.cpp
