######################################################################
# Automatically generated by qmake (1.07a) Sat May 22 20:17:19 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += progressbar.h ProgressBar_test.h
SOURCES += progressbar.cpp ProgressBar_main.cpp ProgressBar_test.cpp
