######################################################################
# Automatically generated by qmake (1.07a) Sat May 22 19:33:01 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += menu.h Menu_test_X.h
SOURCES += menu.cpp Menu_main.cpp Menu_test_X.cpp
