######################################################################
# Automatically generated by qmake (1.07a) Thu May 20 10:46:45 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += lineedits.h LineEdits_test.h
SOURCES += lineedits.cpp LineEdits_main.cpp LineEdits_test.cpp
