######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 12:23:45 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += Messages_test.h MsgBoxView.h
SOURCES += Messages_main.cpp Messages_test.cpp MsgBoxView.cpp
