######################################################################
# Automatically generated by qmake (1.07a) Fri May 21 19:07:55 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += form.h Labels_Pixmap_test.h rlayout.h
SOURCES += form.cpp Labels_Pixmap_main.cpp Labels_Pixmap_test.cpp rlayout.cpp
INSTALLS+=fire.mng