###################################################################################################
#
#    @file   Makefile
#
#    @brief  configuration file to compile the create/remove file test.
#
###################################################################################################
#
#   Copyright (C) 2004, Freescale Semiconductor, Inc. All Rights Reserved
#   THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
#   BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
#   Freescale Semiconductor, Inc.
#     
###################################################################################################
#Revision History:
#                            Modification     Tracking
#Author                          Date          Number    Description of Changes
#-------------------------   ------------    ----------  -------------------------------------------
#S.ZAVJALOV/-----             10/06/2004     TLSbo39741  Initial version
#Ludovic Delaspre / rc149c    21/06/2004     TLSbo39941  VTE 1.3 integration
#L.Delaspre/rc149c            08/12/2004     TLSbo40142   update with Freescale identity
#
###################################################################################################

all:

install:
	@echo "***********************************************"
	@echo "** INSTALL : fs_cr_rm.sh                     **"
	@echo "***********************************************"
	ln -f fs_cr_rm.sh ../../../bin/fs_cr_rm.sh
	@echo

clean:
