######################################################################
# Automatically generated by qmake (1.04a) Sat May 22 12:52:19 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += aux_widgets.h \
           buttons_page.ui.h \
           buttons_page_ext.h \
           metal.h \
           themes.h \
           Themes_test.h \
           wood.h
INTERFACES += buttons_page.ui
SOURCES += aux_widgets.cpp \
           buttons_page_ext.cpp \
           metal.cpp \
           themes.cpp \
           Themes_main.cpp \
           Themes_test.cpp \
           wood.cpp
