###################################################################################################
#
#    @file   Makefile
#
#    @brief  configuration file for UART applications.
#
###################################################################################################
#
#   Copyright (C) 2004, Freescale Semiconductor, Inc. All Rights Reserved
#   THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
#   BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
#   Freescale Semiconductor, Inc.
#     
###################################################################################################
#Revision History:
#                            Modification     Tracking
#Author                          Date          Number    Description of Changes
#-------------------------   ------------    ----------  -------------------------------------------
#Rakesh S Joshi/r65956		     	 24/07/2007      ENGR46100   Initial version 
#
#
###################################################################################################
#Portability: Indicate if this module is portable to other compilers or platforms. 
#             If not, indicate specific reasons why is it not portable.
#
###################################################################################################
SUBDIRS =

all:
install:
	ln -f *.sh ../../bin
	@echo "***********************************************"
	@echo "** INSTALL UART_TESTAPP_7  scripts                   **"
	@echo "***********************************************"
	@echo
clean:
#	@set -e; for i in $(SUBDIRS); do $(MAKE) -C $$i clean distclean; done

