#Copyright 2007-2009 Freescale Semiconductor, Inc. All Rights Reserved.
#
#The code contained herein is licensed under the GNU General Public
#License. You may obtain a copy of the GNU General Public License
#Version 2 or later at the following locations:
#
#http://www.opensource.org/licenses/gpl-license.html
#http://www.gnu.org/copyleft/gpl.html
###################################################################################################
#
#    @file   Makefile
#
#    @brief  configuration file for UART applications.
#
###################################################################################################
#Revision History:
#                            Modification     Tracking
#Author                          Date          Number    Description of Changes
#-------------------------   ------------    ----------  -------------------------------------------
#Rakesh S Joshi		     04/05/2007       ENGR37562   Initial version 
#
#
###################################################################################################
#Portability: Indicate if this module is portable to other compilers or platforms. 
#             If not, indicate specific reasons why is it not portable.
#
###################################################################################################
# SUBDIRS = irda-utils-0.9.16
SUBDIRS =

all:
#	@set -e; for i in $(SUBDIRS); do $(MAKE) -C $$i ; done
install:
#	@set -e; for i in $(SUBDIRS); do $(MAKE) -C $$i install ; done

	ln -f *.sh ../../../bin

	@echo "***********************************************"

	@echo "** INSTALL UART_TESTAPP_7  scripts                   **"

	@echo "***********************************************"

	@echo



clean:
#	@set -e; for i in $(SUBDIRS); do $(MAKE) -C $$i clean distclean; done

