######################################################################
# Automatically generated by qmake (1.07a) Wed May 19 10:03:52 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += sound.h Sound_test_test_X.h
SOURCES += sound.cpp Sound_test_main.cpp Sound_test_test_X.cpp
