#Copyright (C) 2005-2009 Freescale Semiconductor, Inc. All Rights Reserved.
#
#The code contained herein is licensed under the GNU General Public
#License. You may obtain a copy of the GNU General Public License
#Version 2 or later at the following locations:
#
#http://www.opensource.org/licenses/gpl-license.html
#http://www.gnu.org/copyleft/gpl.html
####################################################################################################
#
#    @file   Makefile
#
#    @brief  Makefile for i2c connectivity of pmic13892.
#
####################################################################################################
#Revision History:
#                            Modification     Tracking
#Author/core ID                  Date          Number    Description of Changes
#-------------------------   ------------    ----------  -------------------------------------------
# Blake

all:
install:
	ln -f i2c_connectivity_test.sh ../../bin
	@echo "************************************************"
	@echo "** INSTALL : i2c_connectivity_test.sh               **"
	@echo "************************************************"
	@echo

clean:
	@echo "************************************************"
	@echo "** CLEAN                   **"
	@echo "************************************************"
