####################################################################################################
#
#    @file   Makefile
#
#    @brief  Makefile for i2c connectivity of pmic13892.
#
####################################################################################################
#
#    Copyright (C) 2006, Freescale Semiconductor, Inc. All Rights Reserved
#    THIS SOURCE CODE IS CONFIDENTIAL AND PROPRIETARY AND MAY NOT
#    BE USED OR DISTRIBUTED WITHOUT THE WRITTEN PERMISSION OF
#    Freescale Semiconductor, Inc.
#
####################################################################################################
#Revision History:
#                            Modification     Tracking
#Author/core ID                  Date          Number    Description of Changes
#-------------------------   ------------    ----------  -------------------------------------------
# Blake

all:
install:
	ln -f i2c_connectivity_test.sh ../../bin
	@echo "************************************************"
	@echo "** INSTALL : i2c_connectivity_test.sh               **"
	@echo "************************************************"
	@echo

clean:
	@echo "************************************************"
	@echo "** CLEAN                   **"
	@echo "************************************************"
