######################################################################
# Automatically generated by qmake (1.07a) Thu May 20 10:47:27 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += listbox.h LsitBoxes_test.h
SOURCES += listbox.cpp LsitBoxes_main.cpp LsitBoxes_test.cpp
